require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  AutoCorrect: false
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'db/seeds/*'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/schedule.rb'
    - 'public/uploads/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/ext/*'
    - 'lib/tasks/**/*'
    - 'config/deploy.rb'
    - 'config/deploy/**/*'
  TargetRubyVersion: 2.6.6

Bundler/OrderedGems:
  Enabled: false

# ============================== Rails ==============================
Rails:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/UnknownEnv:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false

# ============================== Documentation ======================
Style/Documentation:
  Enabled: false

# ============================== Metrics ============================
Metrics/ClassLength:
  Max: 180
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'config/routes.rb'
    - 'app/controllers/api/**/*'
    - 'app/controllers/cypress/**/*'
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'config/**/*'
    - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
  Max: 40

# ============================== Naming =============================
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
Naming/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
Naming/MethodParameterName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

# ============================== Layout =============================
Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: case
  IndentOneStep: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
Layout/EmptyLines:
  Enabled: true
  Exclude:
    - 'config/**/*'
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  Exclude:
    - 'app/views/**/*'
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HeredocIndentation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/LineLength:
  Max: 140
  Exclude:
    - 'config/**/*'
    - 'Gemfile'

# ============================== Style ==============================
Style/RescueModifier:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i':    '[]'
    '%w':    '[]'
  Exclude:
    - 'config/routes.rb'
Style/StringLiterals:
  Enabled: true
  Exclude:
    - 'config/**/*'
Style/AsciiComments:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
  Exclude:
    - 'app/models/**/*'
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
Style/RescueStandardError:
  Enabled: true
  EnforcedStyle: explicit
Style/InverseMethods:
  AutoCorrect: false
  Enabled: true
Style/IfUnlessModifier:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# ============================== Lint ==============================
Lint/DuplicateMethods:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
